name: Godot CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Godot Tests
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0
        with:
          cache: true
      - name: Detect Godot binary
        run: |
          if command -v godot4 >/dev/null 2>&1; then
            BIN="$(command -v godot4)"
          elif command -v godot >/dev/null 2>&1; then
            BIN="$(command -v godot)"
          else
            echo "Unable to find Godot binary on PATH" >&2
            exit 1
          fi
          echo "Detected Godot binary: ${BIN}"
          echo "GODOT_BIN=${BIN}" >> "${GITHUB_ENV}"
      - name: Run Godot Headless Tests
        run: pixi run tests
